--------------------------------------------------------
-- Archivo creado  - viernes-junio-14-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FERRETERIA"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FERRETERIA"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FERRETERIA"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FERRETERIA"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FERRETERIA"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORDENCOMPRA
--------------------------------------------------------

   CREATE SEQUENCE  "FERRETERIA"."SEQ_ORDENCOMPRA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ESTADO
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."ESTADO" 
   (	"ID_ESTADO" NUMBER(*,0), 
	"NOMBRE_ESTADO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAMILIA
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."FAMILIA" 
   (	"ID_FAMILIA" NUMBER(*,0), 
	"NOMBRE_FAMILIA" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OC_PROD
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."OC_PROD" 
   (	"PRODUCTO_ID_PRODUCTO" VARCHAR2(17 BYTE), 
	"ORDEN_COMPRA_ID_ORDEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDEN_COMPRA
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."ORDEN_COMPRA" 
   (	"ID_ORDEN" NUMBER(*,0), 
	"FECHA_CREACION" TIMESTAMP (6), 
	"TOTAL_COMPRA" NUMBER(*,0), 
	"ESTADO_ID_ESTADO" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."PERFIL" 
   (	"ID_PERF" NUMBER(*,0), 
	"USUARIO_RUT_USER" NUMBER(*,0), 
	"ROL_ID_ROL" NUMBER(*,0), 
	"USUARIO_RUBRO_ID_RUBRO" NUMBER(*,0), 
	"ESTADO_ID_ESTADO" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_OC
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."PERFIL_OC" 
   (	"PERFIL_ID_PERF" NUMBER(*,0), 
	"ORDEN_COMPRA_ID_ORDEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_PROD
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."PERFIL_PROD" 
   (	"PERFIL_ID_PERF" NUMBER(*,0), 
	"PRODUCTO_ID_PRODUCTO" VARCHAR2(17 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERFIL_VENTA
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."PERFIL_VENTA" 
   (	"PERFIL_ID_PERF" NUMBER(*,0), 
	"VENTA_ID_BOLETA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."PRODUCTO" 
   (	"ID_PRODUCTO" VARCHAR2(17 BYTE), 
	"DESC_PRODUCTO" VARCHAR2(200 BYTE), 
	"PRECIO_UNITARIO" NUMBER(*,0), 
	"PRECIO_COMPRA" NUMBER(*,0), 
	"STOCK" NUMBER(*,0), 
	"STOCK_CRITICO" NUMBER(*,0), 
	"FECHA_VENC" NUMBER(*,0), 
	"TIPO_PRODUCTO_ID_TIPOPROD" NUMBER(*,0), 
	"IMAGEN" BLOB, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ESTADO_ID_ESTADO" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGEN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RECEPCION_OC
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."RECEPCION_OC" 
   (	"ID_RECEPCION" NUMBER(*,0), 
	"FECHA_RECEPCION" TIMESTAMP (6), 
	"ORDEN_COMPRA_ID_ORDEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPORTES
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."REPORTES" 
   (	"ID_REPORTE" NUMBER(*,0), 
	"CONTENIDO_REPORTE" BLOB, 
	"FECHA_REPORTE" TIMESTAMP (6), 
	"PERFIL_ID_PERF" NUMBER(*,0), 
	"TIPO_REPORTE_ID_TREP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENIDO_REPORTE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE_ROL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RUBRO
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."RUBRO" 
   (	"ID_RUBRO" NUMBER(*,0), 
	"NOMBRE_RUBRO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."TIPO_PRODUCTO" 
   (	"ID_TIPOPROD" NUMBER(*,0), 
	"NOMBRE_TIPOPROD" VARCHAR2(30 BYTE), 
	"FAMILIA_ID_FAMILIA" NUMBER(*,0), 
	"TIPOPROD_IMAGEN" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("TIPOPROD_IMAGEN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TIPO_REPORTE
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."TIPO_REPORTE" 
   (	"ID_TREP" NUMBER(*,0), 
	"DESC_TREP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_VENTA
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."TIPO_VENTA" 
   (	"ID_TIPOVENTA" NUMBER(*,0), 
	"NOMBRE_TVT" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."USUARIO" 
   (	"RUT_USER" NUMBER(*,0), 
	"DV_USER" CHAR(1 BYTE), 
	"NOMBRE_USER" VARCHAR2(30 BYTE), 
	"APELLIDO_USER" VARCHAR2(50 BYTE), 
	"EMAIL_USER" VARCHAR2(50 BYTE), 
	"CONTRASENA" VARCHAR2(150 BYTE), 
	"DIRECCION_USER" VARCHAR2(80 BYTE), 
	"FONO_USER" VARCHAR2(15 BYTE), 
	"RUBRO_ID_RUBRO" NUMBER(*,0), 
	"ESTADO_ID_ESTADO" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."VENTA" 
   (	"ID_BOLETA" NUMBER(*,0), 
	"FECHA_BOLETA" TIMESTAMP (6), 
	"TOTAL_VENTA" NUMBER(*,0), 
	"TIPO_VENTA_ID_TIPOVENTA" NUMBER(*,0), 
	"ESTADO_ID_ESTADO" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VNT_PRO
--------------------------------------------------------

  CREATE TABLE "FERRETERIA"."VNT_PRO" 
   (	"VENTA_ID_BOLETA" NUMBER(*,0), 
	"PRODUCTO_ID_PRODUCTO" VARCHAR2(17 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FERRETERIA.ESTADO
SET DEFINE OFF;
Insert into FERRETERIA.ESTADO (ID_ESTADO,NOMBRE_ESTADO) values ('0','DEFAULT');
Insert into FERRETERIA.ESTADO (ID_ESTADO,NOMBRE_ESTADO) values ('-1','ANULADO');
Insert into FERRETERIA.ESTADO (ID_ESTADO,NOMBRE_ESTADO) values ('1','EN CONSTRUCCION');
Insert into FERRETERIA.ESTADO (ID_ESTADO,NOMBRE_ESTADO) values ('2','CREADO');
Insert into FERRETERIA.ESTADO (ID_ESTADO,NOMBRE_ESTADO) values ('3','ENVIADO');
REM INSERTING into FERRETERIA.FAMILIA
SET DEFINE OFF;
Insert into FERRETERIA.FAMILIA (ID_FAMILIA,NOMBRE_FAMILIA) values ('1','Construccion');
Insert into FERRETERIA.FAMILIA (ID_FAMILIA,NOMBRE_FAMILIA) values ('2','Herramientas');
Insert into FERRETERIA.FAMILIA (ID_FAMILIA,NOMBRE_FAMILIA) values ('3','Electricidad');
Insert into FERRETERIA.FAMILIA (ID_FAMILIA,NOMBRE_FAMILIA) values ('4','Pintura');
Insert into FERRETERIA.FAMILIA (ID_FAMILIA,NOMBRE_FAMILIA) values ('5','Baño y Fontanería');
Insert into FERRETERIA.FAMILIA (ID_FAMILIA,NOMBRE_FAMILIA) values ('6','Jardin');
REM INSERTING into FERRETERIA.OC_PROD
SET DEFINE OFF;
REM INSERTING into FERRETERIA.ORDEN_COMPRA
SET DEFINE OFF;
REM INSERTING into FERRETERIA.PERFIL
SET DEFINE OFF;
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('1','18888888','1','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('2','17777777','4','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('3','20854729','5','5','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('4','16856856','3','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('5','17828395','3','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('6','17828395','4','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('10','19649987','4','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('7','19362287','4','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('8','9030310','4','1','0');
Insert into FERRETERIA.PERFIL (ID_PERF,USUARIO_RUT_USER,ROL_ID_ROL,USUARIO_RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('11','18622907','4','1','1');
REM INSERTING into FERRETERIA.PERFIL_OC
SET DEFINE OFF;
REM INSERTING into FERRETERIA.PERFIL_PROD
SET DEFINE OFF;
REM INSERTING into FERRETERIA.PERFIL_VENTA
SET DEFINE OFF;
REM INSERTING into FERRETERIA.PRODUCTO
SET DEFINE OFF;
Insert into FERRETERIA.PRODUCTO (ID_PRODUCTO,DESC_PRODUCTO,PRECIO_UNITARIO,PRECIO_COMPRA,STOCK,STOCK_CRITICO,FECHA_VENC,TIPO_PRODUCTO_ID_TIPOPROD,NOMBRE,ESTADO_ID_ESTADO) values ('1','Clavos grandes, medida 60cm','5','6','5000','0',null,'1','Clavos 60cm marca Chancho','0');
REM INSERTING into FERRETERIA.RECEPCION_OC
SET DEFINE OFF;
REM INSERTING into FERRETERIA.REPORTES
SET DEFINE OFF;
REM INSERTING into FERRETERIA.ROL
SET DEFINE OFF;
Insert into FERRETERIA.ROL (ID_ROL,NOMBRE_ROL) values ('1','ADMINISTRADOR');
Insert into FERRETERIA.ROL (ID_ROL,NOMBRE_ROL) values ('2','EMPLEADO');
Insert into FERRETERIA.ROL (ID_ROL,NOMBRE_ROL) values ('3','VENDEDOR');
Insert into FERRETERIA.ROL (ID_ROL,NOMBRE_ROL) values ('4','CLIENTE');
Insert into FERRETERIA.ROL (ID_ROL,NOMBRE_ROL) values ('5','PROVEEDOR');
REM INSERTING into FERRETERIA.RUBRO
SET DEFINE OFF;
Insert into FERRETERIA.RUBRO (ID_RUBRO,NOMBRE_RUBRO) values ('1','NO APLICA');
Insert into FERRETERIA.RUBRO (ID_RUBRO,NOMBRE_RUBRO) values ('2','CONSTRUCCION');
Insert into FERRETERIA.RUBRO (ID_RUBRO,NOMBRE_RUBRO) values ('3','PINTURAS');
Insert into FERRETERIA.RUBRO (ID_RUBRO,NOMBRE_RUBRO) values ('4','HERRAMIENTAS');
Insert into FERRETERIA.RUBRO (ID_RUBRO,NOMBRE_RUBRO) values ('5','VARIADO');
REM INSERTING into FERRETERIA.TIPO_PRODUCTO
SET DEFINE OFF;
Insert into FERRETERIA.TIPO_PRODUCTO (ID_TIPOPROD,NOMBRE_TIPOPROD,FAMILIA_ID_FAMILIA) values ('1','CLAVOS','1');
Insert into FERRETERIA.TIPO_PRODUCTO (ID_TIPOPROD,NOMBRE_TIPOPROD,FAMILIA_ID_FAMILIA) values ('4','CABLES','1');
Insert into FERRETERIA.TIPO_PRODUCTO (ID_TIPOPROD,NOMBRE_TIPOPROD,FAMILIA_ID_FAMILIA) values ('6','TUBERIA','2');
Insert into FERRETERIA.TIPO_PRODUCTO (ID_TIPOPROD,NOMBRE_TIPOPROD,FAMILIA_ID_FAMILIA) values ('7','CONTROL PLAGAS','2');
Insert into FERRETERIA.TIPO_PRODUCTO (ID_TIPOPROD,NOMBRE_TIPOPROD,FAMILIA_ID_FAMILIA) values ('2','TUERCAS','1');
Insert into FERRETERIA.TIPO_PRODUCTO (ID_TIPOPROD,NOMBRE_TIPOPROD,FAMILIA_ID_FAMILIA) values ('3','TORNILLOS','2');
REM INSERTING into FERRETERIA.TIPO_REPORTE
SET DEFINE OFF;
REM INSERTING into FERRETERIA.TIPO_VENTA
SET DEFINE OFF;
Insert into FERRETERIA.TIPO_VENTA (ID_TIPOVENTA,NOMBRE_TVT) values ('1','BOLETA');
Insert into FERRETERIA.TIPO_VENTA (ID_TIPOVENTA,NOMBRE_TVT) values ('2','FACTURA');
REM INSERTING into FERRETERIA.USUARIO
SET DEFINE OFF;
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('18888888','1','PEPITO','PAGADOBLE','asd@asd.cl','asd','calle falsa 123','123123123','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('17777777','K','PEPA','PIG','thux_pepitaxshishi@boss.cl','shishilife','puente alto 44','2272222','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('20854729','3','Metales ltda',null,'contacto@metales.cl','metales123','Av vitacura 6000','22873921','5','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('16856856','5','DON','DA','dondax@axe.cl','123empleado','Av. Algo 21','+5695554342','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('17828395','K','Charlie','Badulaque','callme@cachorritas.cl','doncharlie123','No existe 54','+569857832','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('19649987','3','Jonathan','PeÃ±a','jony2012@gmail.com','28970aab014cf552b44cf480a4e9a9db47cfc1d6ecd29d8a23a8b4a0aba7395f33ca1695fde9f9dd36aa3f4eb4404c02a29454fb47632d68f16e26ffeb7bed42','Pasaje 123','988888888','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('9030310','4','Emilia','Sales','lordpqueno10@gmail.com','898fc97c4353a3049f5eb73d6bafffc47353e9c4bab37e832ae72f1c57dad2ad14dafcd805093b3776c4edcbc8c880212ca47fc53a083cd437d6a97c5983ef76','Avenida alfredo silva carvallo #737','989985158','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('19362287','9','Francisco','Farias','lordpqueno7@gmail.com','898fc97c4353a3049f5eb73d6bafffc47353e9c4bab37e832ae72f1c57dad2ad14dafcd805093b3776c4edcbc8c880212ca47fc53a083cd437d6a97c5983ef76','avenida alfredo silva carvallo #737','989985158','1','0');
Insert into FERRETERIA.USUARIO (RUT_USER,DV_USER,NOMBRE_USER,APELLIDO_USER,EMAIL_USER,CONTRASENA,DIRECCION_USER,FONO_USER,RUBRO_ID_RUBRO,ESTADO_ID_ESTADO) values ('18622907','k','matias','fernandez','ma@ma.cl','c63577295fdc5b8349f1a815551146f0928cff3f1c5d60204afc5005c781fa93f5fc3f2ae71a9f899e2e779e23ef7363b033de1d095225942bf5852ef32c5e75','calle 123','977676889','1','1');
REM INSERTING into FERRETERIA.VENTA
SET DEFINE OFF;
REM INSERTING into FERRETERIA.VNT_PRO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TIPO_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."TIPO_PRODUCTO_PK" ON "FERRETERIA"."TIPO_PRODUCTO" ("ID_TIPOPROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEPCION_OC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."RECEPCION_OC_PK" ON "FERRETERIA"."RECEPCION_OC" ("ID_RECEPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."VENTA_PK" ON "FERRETERIA"."VENTA" ("ID_BOLETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."PERFIL_PK" ON "FERRETERIA"."PERFIL" ("ID_PERF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEPCION_OC__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."RECEPCION_OC__IDX" ON "FERRETERIA"."RECEPCION_OC" ("ORDEN_COMPRA_ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDEN_COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."ORDEN_COMPRA_PK" ON "FERRETERIA"."ORDEN_COMPRA" ("ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."ROL_PK" ON "FERRETERIA"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERFIL_VENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."PERFIL_VENTA_PK" ON "FERRETERIA"."PERFIL_VENTA" ("PERFIL_ID_PERF", "VENTA_ID_BOLETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_VENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."TIPO_VENTA_PK" ON "FERRETERIA"."TIPO_VENTA" ("ID_TIPOVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RUBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."RUBRO_PK" ON "FERRETERIA"."RUBRO" ("ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FAMILIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."FAMILIA_PK" ON "FERRETERIA"."FAMILIA" ("ID_FAMILIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."USUARIO_PK" ON "FERRETERIA"."USUARIO" ("RUT_USER", "RUBRO_ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OC_PROD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."OC_PROD_PK" ON "FERRETERIA"."OC_PROD" ("ORDEN_COMPRA_ID_ORDEN", "PRODUCTO_ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."PRODUCTO_PK" ON "FERRETERIA"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."ESTADO_PK" ON "FERRETERIA"."ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."REPORTES_PK" ON "FERRETERIA"."REPORTES" ("ID_REPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERFIL_PROD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."PERFIL_PROD_PK" ON "FERRETERIA"."PERFIL_PROD" ("PERFIL_ID_PERF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_REPORTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."TIPO_REPORTE_PK" ON "FERRETERIA"."TIPO_REPORTE" ("ID_TREP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERFIL_OC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERRETERIA"."PERFIL_OC_PK" ON "FERRETERIA"."PERFIL_OC" ("PERFIL_ID_PERF", "ORDEN_COMPRA_ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure SP_ORDENCOMPRA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERRETERIA"."SP_ORDENCOMPRA" (p_empleado NUMBER ) IS
v_idoc NUMBER;
v_fecha TIMESTAMP := SYSTIMESTAMP;
v_totalcompra NUMBER;
v_estado NUMBER := 1;

BEGIN

SELECT seq_ordencompra.nextval
INTO v_idoc
FROM DUAL;



INSERT INTO ORDEN_COMPRA (ID_ORDEN,FECHA_CREACION,TOTAL_COMPRA,ESTADO_ID_ESTADO) 
VALUES (v_idoc,v_fecha,0,v_estado);

INSERT INTO PERFIL_OC(PERFIL_ID_PERF, ORDEN_COMPRA_ID_ORDEN) 
VALUES (p_empleado, v_idoc);

END;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "FERRETERIA"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "FERRETERIA"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'I5AH1EV343WEW59X1ZGX7VNZMK781E';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  Constraints for Table OC_PROD
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."OC_PROD" ADD CONSTRAINT "OC_PROD_PK" PRIMARY KEY ("ORDEN_COMPRA_ID_ORDEN", "PRODUCTO_ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."OC_PROD" MODIFY ("ORDEN_COMPRA_ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."OC_PROD" MODIFY ("PRODUCTO_ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_PK" PRIMARY KEY ("ID_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."ORDEN_COMPRA" MODIFY ("ESTADO_ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."ORDEN_COMPRA" MODIFY ("TOTAL_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."ORDEN_COMPRA" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."ORDEN_COMPRA" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORTES
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."REPORTES" ADD CONSTRAINT "REPORTES_PK" PRIMARY KEY ("ID_REPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."REPORTES" MODIFY ("TIPO_REPORTE_ID_TREP" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."REPORTES" MODIFY ("PERFIL_ID_PERF" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."REPORTES" MODIFY ("FECHA_REPORTE" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."REPORTES" MODIFY ("CONTENIDO_REPORTE" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."REPORTES" MODIFY ("ID_REPORTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL_VENTA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL_VENTA" ADD CONSTRAINT "PERFIL_VENTA_PK" PRIMARY KEY ("PERFIL_ID_PERF", "VENTA_ID_BOLETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL_VENTA" MODIFY ("VENTA_ID_BOLETA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL_VENTA" MODIFY ("PERFIL_ID_PERF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FAMILIA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."FAMILIA" ADD CONSTRAINT "FAMILIA_PK" PRIMARY KEY ("ID_FAMILIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."FAMILIA" MODIFY ("NOMBRE_FAMILIA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."FAMILIA" MODIFY ("ID_FAMILIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."ROL" MODIFY ("NOMBRE_ROL" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPCION_OC
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."RECEPCION_OC" ADD CONSTRAINT "RECEPCION_OC_PK" PRIMARY KEY ("ID_RECEPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."RECEPCION_OC" MODIFY ("ORDEN_COMPRA_ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."RECEPCION_OC" MODIFY ("FECHA_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."RECEPCION_OC" MODIFY ("ID_RECEPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_REPORTE
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."TIPO_REPORTE" ADD CONSTRAINT "TIPO_REPORTE_PK" PRIMARY KEY ("ID_TREP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."TIPO_REPORTE" MODIFY ("DESC_TREP" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."TIPO_REPORTE" MODIFY ("ID_TREP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL_PROD
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL_PROD" ADD CONSTRAINT "PERFIL_PROD_PK" PRIMARY KEY ("PERFIL_ID_PERF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL_PROD" MODIFY ("PRODUCTO_ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL_PROD" MODIFY ("PERFIL_ID_PERF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("ESTADO_ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("RUT_USER", "RUBRO_ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("RUBRO_ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("FONO_USER" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("DIRECCION_USER" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("EMAIL_USER" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("NOMBRE_USER" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("DV_USER" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."USUARIO" MODIFY ("RUT_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_VENTA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."TIPO_VENTA" ADD CONSTRAINT "TIPO_VENTA_PK" PRIMARY KEY ("ID_TIPOVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."TIPO_VENTA" MODIFY ("NOMBRE_TVT" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."TIPO_VENTA" MODIFY ("ID_TIPOVENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."VENTA" MODIFY ("ESTADO_ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."VENTA" ADD CONSTRAINT "VENTA_PK" PRIMARY KEY ("ID_BOLETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."VENTA" MODIFY ("TIPO_VENTA_ID_TIPOVENTA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."VENTA" MODIFY ("TOTAL_VENTA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."VENTA" MODIFY ("FECHA_BOLETA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."VENTA" MODIFY ("ID_BOLETA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUBRO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."RUBRO" ADD CONSTRAINT "RUBRO_PK" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."RUBRO" MODIFY ("NOMBRE_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."RUBRO" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL" MODIFY ("ESTADO_ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL" ADD CONSTRAINT "PERFIL_PK" PRIMARY KEY ("ID_PERF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL" MODIFY ("USUARIO_RUBRO_ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL" MODIFY ("ROL_ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL" MODIFY ("USUARIO_RUT_USER" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL" MODIFY ("ID_PERF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL_OC
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL_OC" ADD CONSTRAINT "PERFIL_OC_PK" PRIMARY KEY ("PERFIL_ID_PERF", "ORDEN_COMPRA_ID_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL_OC" MODIFY ("ORDEN_COMPRA_ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PERFIL_OC" MODIFY ("PERFIL_ID_PERF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."ESTADO" ADD CONSTRAINT "ESTADO_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."ESTADO" MODIFY ("NOMBRE_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."ESTADO" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VNT_PRO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."VNT_PRO" MODIFY ("PRODUCTO_ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."VNT_PRO" MODIFY ("VENTA_ID_BOLETA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."TIPO_PRODUCTO" ADD CONSTRAINT "TIPO_PRODUCTO_PK" PRIMARY KEY ("ID_TIPOPROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."TIPO_PRODUCTO" MODIFY ("NOMBRE_TIPOPROD" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."TIPO_PRODUCTO" MODIFY ("ID_TIPOPROD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("ESTADO_ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("TIPO_PRODUCTO_ID_TIPOPROD" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("STOCK_CRITICO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("PRECIO_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("PRECIO_UNITARIO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("DESC_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "FERRETERIA"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OC_PROD
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."OC_PROD" ADD CONSTRAINT "OC_PROD_ORDEN_COMPRA_FK" FOREIGN KEY ("ORDEN_COMPRA_ID_ORDEN")
	  REFERENCES "FERRETERIA"."ORDEN_COMPRA" ("ID_ORDEN") ENABLE;
  ALTER TABLE "FERRETERIA"."OC_PROD" ADD CONSTRAINT "OC_PROD_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO_ID_PRODUCTO")
	  REFERENCES "FERRETERIA"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_ESTADO_FK" FOREIGN KEY ("ESTADO_ID_ESTADO")
	  REFERENCES "FERRETERIA"."ESTADO" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL" ADD CONSTRAINT "PERFIL_ESTADO_FK" FOREIGN KEY ("ESTADO_ID_ESTADO")
	  REFERENCES "FERRETERIA"."ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL" ADD CONSTRAINT "PERFIL_ROL_FK" FOREIGN KEY ("ROL_ID_ROL")
	  REFERENCES "FERRETERIA"."ROL" ("ID_ROL") ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL" ADD CONSTRAINT "PERFIL_USUARIO_FK" FOREIGN KEY ("USUARIO_RUT_USER", "USUARIO_RUBRO_ID_RUBRO")
	  REFERENCES "FERRETERIA"."USUARIO" ("RUT_USER", "RUBRO_ID_RUBRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_OC
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL_OC" ADD CONSTRAINT "PERFIL_OC_ORDEN_COMPRA_FK" FOREIGN KEY ("ORDEN_COMPRA_ID_ORDEN")
	  REFERENCES "FERRETERIA"."ORDEN_COMPRA" ("ID_ORDEN") ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL_OC" ADD CONSTRAINT "PERFIL_OC_PERFIL_FK" FOREIGN KEY ("PERFIL_ID_PERF")
	  REFERENCES "FERRETERIA"."PERFIL" ("ID_PERF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_PROD
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL_PROD" ADD CONSTRAINT "PERFIL_PROD_PERFIL_FK" FOREIGN KEY ("PERFIL_ID_PERF")
	  REFERENCES "FERRETERIA"."PERFIL" ("ID_PERF") ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL_PROD" ADD CONSTRAINT "PERFIL_PROD_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO_ID_PRODUCTO")
	  REFERENCES "FERRETERIA"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_VENTA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PERFIL_VENTA" ADD CONSTRAINT "PERFIL_VENTA_PERFIL_FK" FOREIGN KEY ("PERFIL_ID_PERF")
	  REFERENCES "FERRETERIA"."PERFIL" ("ID_PERF") ENABLE;
  ALTER TABLE "FERRETERIA"."PERFIL_VENTA" ADD CONSTRAINT "PERFIL_VENTA_VENTA_FK" FOREIGN KEY ("VENTA_ID_BOLETA")
	  REFERENCES "FERRETERIA"."VENTA" ("ID_BOLETA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_ESTADO_FK" FOREIGN KEY ("ESTADO_ID_ESTADO")
	  REFERENCES "FERRETERIA"."ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "FERRETERIA"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_TIPO_PRODUCTO_FK" FOREIGN KEY ("TIPO_PRODUCTO_ID_TIPOPROD")
	  REFERENCES "FERRETERIA"."TIPO_PRODUCTO" ("ID_TIPOPROD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEPCION_OC
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."RECEPCION_OC" ADD CONSTRAINT "RECEPCION_OC_ORDEN_COMPRA_FK" FOREIGN KEY ("ORDEN_COMPRA_ID_ORDEN")
	  REFERENCES "FERRETERIA"."ORDEN_COMPRA" ("ID_ORDEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORTES
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."REPORTES" ADD CONSTRAINT "REPORTES_PERFIL_FK" FOREIGN KEY ("PERFIL_ID_PERF")
	  REFERENCES "FERRETERIA"."PERFIL" ("ID_PERF") ENABLE;
  ALTER TABLE "FERRETERIA"."REPORTES" ADD CONSTRAINT "REPORTES_TIPO_REPORTE_FK" FOREIGN KEY ("TIPO_REPORTE_ID_TREP")
	  REFERENCES "FERRETERIA"."TIPO_REPORTE" ("ID_TREP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."TIPO_PRODUCTO" ADD FOREIGN KEY ("FAMILIA_ID_FAMILIA")
	  REFERENCES "FERRETERIA"."FAMILIA" ("ID_FAMILIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."USUARIO" ADD CONSTRAINT "USUARIO_ESTADO_FK" FOREIGN KEY ("ESTADO_ID_ESTADO")
	  REFERENCES "FERRETERIA"."ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "FERRETERIA"."USUARIO" ADD CONSTRAINT "USUARIO_RUBRO_FK" FOREIGN KEY ("RUBRO_ID_RUBRO")
	  REFERENCES "FERRETERIA"."RUBRO" ("ID_RUBRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."VENTA" ADD CONSTRAINT "VENTA_ESTADO_FK" FOREIGN KEY ("ESTADO_ID_ESTADO")
	  REFERENCES "FERRETERIA"."ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "FERRETERIA"."VENTA" ADD CONSTRAINT "VENTA_TIPO_VENTA_FK" FOREIGN KEY ("TIPO_VENTA_ID_TIPOVENTA")
	  REFERENCES "FERRETERIA"."TIPO_VENTA" ("ID_TIPOVENTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VNT_PRO
--------------------------------------------------------

  ALTER TABLE "FERRETERIA"."VNT_PRO" ADD CONSTRAINT "VNT_PRO_PRODUCTO_FK" FOREIGN KEY ("PRODUCTO_ID_PRODUCTO")
	  REFERENCES "FERRETERIA"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "FERRETERIA"."VNT_PRO" ADD CONSTRAINT "VNT_PRO_VENTA_FK" FOREIGN KEY ("VENTA_ID_BOLETA")
	  REFERENCES "FERRETERIA"."VENTA" ("ID_BOLETA") ENABLE;
